config/routes.rb
Rails.application.routes.draw do
  get 'results/index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
  }
  root 'articles#index'

  get 'upanel', to: 'static#upanel', as: 'upanel'

  namespace :admin do
    get 'cpanel', to: 'admin#cpanel', as: 'cpanel'
    resources :users do
      member do
        patch 'remove_from_department', to: 'users#remove_from_department'
      end
    end
    resources :departments
    resources :roles
    get 'history', to: 'history#index', as: 'history'
  end

  resources :secure_records
  resources :notes
  resources :articles

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/department.rb
class Department < ApplicationRecord
  validates :key, :name, presence: true, uniqueness: true
  audited
  has_many :users

  def show_name
    if self.name.present?
      self.name
    else
      self.key
    end
  end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :require_admin?

  def index
  end

  def show
    @search_results = User.search_everywhere(params[:query])
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new department_params
    if @department.save
      flash[:notice] = "Отдел успешно создан"
    else
      flash[:alert] = @department.errors.full_messages.join("<br>").html_safe
    end
  end

  def edit
  end

  def update
    if @department.update department_params
      flash.now[:notice] = "Отдел успешно обновлён."
    else
      flash.now[:alert] = @department.errors.full_messages.join("<br>").html_safe
    end
  end



  def destroy
    if @department.users.present?
      flash.now[:alert] = "Отдел не может быть удалён, так как в нём присутствуют пользователи."
      return
    end

    if @department.destroy
      flash.now[:alert] = "Отдел успешно удалён."
    else
      flash.now[:alert] = @department.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:key, :name, user_ids: [])
  end

  def require_admin?
    unless current_user.admin?
      render :plain => 'Вы не администратор'
    end
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new department_params
    if @department.save
      flash[:notice] = "Отдел успешно создан"
    else
      flash[:alert] = @department.errors.full_messages.join("<br>").html_safe
    end
  end

  def edit
  end

  def update
    if @department.update department_params
      flash.now[:notice] = "Отдел успешно обновлён."
    else
      flash.now[:alert] = @department.errors.full_messages.join("<br>").html_safe
    end
  end



  def destroy
    if @department.users.present?
      flash.now[:alert] = "Отдел не может быть удалён, так как в нём присутствуют пользователи."
      return
    end

    if @department.destroy
      flash.now[:alert] = "Отдел успешно удалён."
    else
      flash.now[:alert] = @department.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:key, :name, user_ids: [])
  end

end

app/views/admin/departments/_department_info.erb
<%=turbo_frame_tag "department-info" do %>
  <div class="center-and-right-column column-title">
    Информация об отделе
    <div class="title-login">
      <%= @department.show_name %>
    </div>
    <button class="close-turbo-frame btn btn-danger" data-frame-id="department-info">X</button>
  </div>

  <div class="show-wrapper department-show-wrapper">

    <div class="show-container">

      <div class="info-container">

        <div class="form-wrapper">
          <%= form_tag admin_department_path(@department), method: :get, role: 'search' do %>
            <div class="form-field search-wrapper">
              <%= text_field_tag :query, params[:query], placeholder: 'Поиск', class: 'search-field' %>
              <%= submit_tag 'Поиск', class: 'btn btn-lg' %>
            </div>
          <% end %>
        </div>

        <% if @search_results.present? %>
          <% if @search_results.where(department_id: @department).present? %>
            <br>
            Результаты поиска : <br>
            <% @search_results.where(department_id: @department).each do |result| %>
              <details class="show-item">
                <summary class="item-links">
                  <% result = UserDecorator.decorate(result) %>
                  <%= link_to result.show_full_name, admin_user_path(result), class: "item-name", data: { turbo_frame: "user-info" } %>
                </summary>
                <div class="user-email">
                  <%= result.email %>
                </div>
                <div class="user-department">
                  <%= result.department.name %>
                </div>
                <div class="item-actions">
                  <%= link_to 'Инфо', admin_user_path(result), class: "link", data: { turbo_frame: "user-info" } %>
                  <%= link_to 'Изменить', edit_admin_user_path(result), method: :get, class: "link", data: { turbo_frame: "user-edit" } %>
                </div>
              </details>
            <% end %>
            <br>
          <% end %>
        <% end %>


        <div class="users-table">
          <% @department.users.each do |user| %>

            <details class="show-item">

              <summary class="item-links">
                <% user = UserDecorator.decorate(user) %>
                <%= link_to user.show_full_name, admin_user_path(user), class: "item-name", data: { turbo_frame: "user-info" } %>
              </summary>

              <div class="user-email">
                <%= user.email %>
              </div>

              <div class="user-department">
                <%= user.department.name %>
              </div>

              <div class="item-actions">
                <%= link_to 'Инфо', admin_user_path(user), class: "link", data: { turbo_frame: "user-info" } %>
                <%= link_to 'Изменить', edit_admin_user_path(user), method: :get, class: "link", data: { turbo_frame: "user-edit" } %>
              </div>

            </details>

          <% end %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/departments/_departments.erb
<%= turbo_frame_tag "left-column" do %>

  <% departments = Department.all.order created_at: :desc %>

  <div class="list-wrapper">
    <div class="list-title column-title">
      <div class="menu-button-wrapper">
        <%= button_to 'Пользователи', admin_users_path, data: { turbo_frame: "left-column"}, method: :get, class: "menu-button" %>
      </div>
      <div class="menu-button-wrapper">
        <%= button_to 'Роли', admin_roles_path, data: { turbo_frame: "left-column" }, method: :get, class: "menu-button" %>
      </div>
      <div class="title-menu">
        <div class="title-text">
          Отделы
        </div>
      </div>
    </div>

      <%= button_to 'Создать новый отдел', new_admin_department_path, data: { turbo_frame: "department-new" }, class: "plus-btn", method: :get %>

    <div class="list-container">
      <% departments.each_with_index do |department, index| %>
        <div class="item <%= index.odd? ? 'odd' : 'even' %>">
          <%= turbo_frame_tag department do %>
            <div class="item-links">
              <%= link_to (department.name.present? ? department.name : department.key), admin_department_path(department), class: "item-name", data: { turbo_frame: "department-info" } %>
              <div class="item-actions">
                <%= link_to 'Инфо', admin_department_path(department), class: "link", data: { turbo_frame: "department-info" } %>
                <%= link_to 'Изменить', edit_admin_department_path(department), method: :get, class: "link", data: { turbo_frame: "department-edit" } %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/departments/_form_edit.erb
<%= turbo_frame_tag "department-edit" do %>

  <div class="center-and-right-column column-title">
    Редактирование отдела
    <div class="title-login">
      <%= @department.show_name %>
    </div>
    <button class="close-turbo-frame btn btn-danger" data-frame-id="department-edit">X</button>
  </div>

  <div class="form-wrapper">
    <%= form_for @department, url: admin_department_path(@department), method: :patch, html: { class: 'form-edit' } do |f| %>

<!--      <div id="flash">-->
        <%#= render partial: 'shared/flash' %>
<!--      </div>-->

      <div class="form-field">
        <%= f.label :key, 'Ключ' %>
        <%= f.text_field :key, autofocus: true, required: true %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Название' %>
        <%= f.text_field :name, autofocus: true, required: true %>
      </div>

      <% if @department.users.present? %>
        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title">Пользователи в этом отделе</legend>
          <div class="checkbox-table">
            <%= f.collection_check_boxes :user_ids, @department.users, :id, -> (user) { UserDecorator.decorate(user).show_full_name } do |user| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= user.label %>
                </div>
                <div class="checkbox-input">
                  <%= user.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>
      <% end %>

      <% if User.where(department: nil).present? %>
        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title">Пользователи без отдела</legend>
          <div class="checkbox-table">
            <%= f.collection_check_boxes :user_ids, User.where(department: nil), :id, -> (user) { UserDecorator.decorate(user).show_full_name } do |user| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= user.label %>
                </div>
                <div class="checkbox-input">
                  <%= user.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>
      <% end %>

      <div class="form-actions">
        <%= f.submit 'Сохранить изменения', class: 'btn btn-lg' %>
        <%= link_to 'Удалить отдел', admin_department_path(@department), data: { turbo_method: :delete, turbo_confirm: "Удалить роль #{@department.key}?" }, class: 'btn btn-danger btn-lg' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/departments/_form_new.erb
<%= turbo_frame_tag "department-new" do %>
  <div class="center-and-right-column column-title">
    Создание нового отдела
    <button class="close-turbo-frame btn btn-danger" data-frame-id="department-new">X</button>
  </div>
  <div class="form-wrapper">
    <%= form_for @department, url: admin_departments_path, local: true, html: { class: 'form-edit' } do |f| %>

<!--      <div id="flash">-->
        <%#= render partial: 'shared/flash' %>
<!--      </div>-->

      <div class="form-field">
        <%= f.label :key, 'Ключ' %>
        <%= f.text_field :key, autofocus: true, required: true %>
      </div>
      <div class="form-field">
        <%= f.label :name, 'Название' %>
        <%= f.text_field :name, required: true %>
      </div>
      <% if User.where(department: nil?).present? %>
        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title">Добавить пользователей в отдел</legend>
          <div class="checkbox-table">
            <%= f.collection_check_boxes :user_ids, User.where(department: 1), :id, -> (user) { user.login } do |user| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= user.label %>
                </div>
                <div class="checkbox-input">
                  <%= user.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>
      <% end %>
      <div class="form-actions">
        <%= f.submit 'Сохранить', class: 'btn btn-lg' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/departments/create.turbo_stream.erb
<%= turbo_stream.update("left-column") do
  render 'departments'
end %>

<%= prepend_flash %>

app/views/admin/departments/destroy.turbo_stream.erb
<%= turbo_stream.update("left-column") do
  render 'departments'
end %>

<%= turbo_stream.update("department-edit") do
end %>

app/views/admin/departments/edit.erb
<%= render 'form_edit' %>

app/views/admin/departments/index.erb
<%= turbo_frame_tag "left-column" do %>
  <%= render 'departments' %>
<% end %>

app/views/admin/departments/new.erb
<%= render 'form_new' %>

app/views/admin/departments/show.erb
<%= render 'department_info' %>

app/views/admin/departments/update.turbo_stream.erb
<%= turbo_stream.update("department-edit") do
  render 'form_edit'
end %>

<%= turbo_stream.update("department-info") do
  render 'department_info'
end %>

<%= turbo_stream.update("left-column") do
  render 'departments'
end %>

<%#= prepend_flash %>