config/routes.rb
Rails.application.routes.draw do
  get 'results/index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
  }
  root 'articles#index'

  get 'upanel', to: 'static#upanel', as: 'upanel'

  namespace :admin do
    get 'cpanel', to: 'admin#cpanel', as: 'cpanel'
    resources :users do
      member do
        patch 'remove_from_department', to: 'users#remove_from_department'
      end
    end
    resources :departments
    resources :roles
    get 'history', to: 'history#index', as: 'history'
  end

  resources :secure_records
  resources :notes
  resources :articles

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_everywhere, against: [:login, :email, :first_name, :last_name]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :trackable, :timeoutable,
         :registerable

  validates :login, :email, presence: true, uniqueness: true
  validates :department_id, allow_nil: true, presence: true

  belongs_to :role
  belongs_to :department
  has_and_belongs_to_many :credentials
  has_many :secure_records
  has_many :notes

  audited


  # role definition
  def admin?
    self.role.key == 'admin'
  end

  # credentials check

  def can_edit_own_profile? # ok
    self.credentials.include?(Credential.find_by(key: 'can_edit_own_profile'))
  end

  def can_edit_user?
    User.find_by(id: self.id).credentials.include?(Credential.find_by(key: 'can_edit_user'))
  end

  def can_assign_department_to_user?
    User.find_by(id: self.id).credentials.include?(Credential.find_by(key: 'can_assign_department_to_user'))
  end

  def can_working_with_articles?
    User.find_by(id: self.id).credentials.include?(Credential.find_by(key: 'can_working_with_articles'))
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user!, only: %i[show edit update destroy]
  before_action :require_admin?

  def index
    @users = User.order created_at: :desc
    @search_results = User.search_everywhere(params[:query])
  end

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      flash.now[:notice] = "Пользователь успешно обновлен"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def destroy
    if @user.admin?
      flash.now[:alert] = "Нельзя удалить администратора"
      return
    end

    if @user.destroy
      flash.now[:alert] = "Пользователь успешно удален"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def remove_from_department
    @user = User.find(params[:id])
    @user.department = nil
    if @user.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("user-info", partial: "user_info") }
      end
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :first_name, :last_name, :department_id, :password, :role_id, credential_ids: [])
  end

  def set_user!
    @user = User.find(params[:id]).decorate
  end

  def require_admin?
    unless current_user.admin?
      render :plain => 'Вы не администратор'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user!, only: %i[show edit update destroy]

  def index
    @users = User.order created_at: :desc
  end

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      flash.now[:notice] = "Пользователь успешно обновлен"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def destroy
    if @user.admin?
      flash.now[:alert] = "Нельзя удалить администратора"
      return
    end

    if @user.destroy
      flash.now[:alert] = "Пользователь успешно удален"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def remove_from_department
    @user = User.find(params[:id])
    @user.department_id = Department.find_by(key: "nil_department", name: "Нулевой отдел").id
    if @user.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("user-info", partial: "user_info") }
      end
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :first_name, :last_name, :department_id, :password, :role_id, credential_ids: [])
  end

  def set_user!
    @user = User.find(params[:id]).decorate
  end

end

app/views/users/_form_edit.erb
<%= turbo_frame_tag "user-edit" do %>

  <div class="center-and-right-column column-title">Редактирование пользователя:
    <div class="title-login"><%= @user.login %></div>
    <button class="close-turbo-frame" data-frame-id="user-edit">X</button>
  </div>

  <div class="form-wrapper form-edit">

    <% if current_user.can_edit_user? %>

      <%= form_for @user, url: user_path(@user), method: :patch do |f| %>

        <div id="flash">
          <%= render partial: 'shared/flash' %>
        </div>

        <div class="form-field">
          <%= f.label t('.login') %>
          <%= f.text_field :login, autofocus: true, required: true %>
        </div>

        <div class="form-field">
          <%= f.label t('.email') %>
          <%= f.email_field :email %>
        </div>

        <div class="form-field">
          <%= f.label "Имя" %>
          <%= f.text_field :first_name %>
        </div>

        <div class="form-field">
          <%= f.label "Фамилия" %>
          <%= f.text_field :last_name %>
        </div>

        <div class="form-field">
          <%= f.label t('activerecord.attributes.user.role') %>
          <%= f.collection_select :role_id, Role.all, :id, -> (role) { role.name.present? ? role.name : role.key } %>
        </div>

        <% if current_user.can_assign_department_to_user? %>
          <div class="form-field">
            <%= f.label t('.department') %>
            <%= f.collection_select :department_id, Department.all, :id, :name %>
            <%= link_to 'Удалить из отдела', remove_from_department_user_path(@user), data: { turbo_method: :patch, turbo_confirm: 'Удалить пользователя из отдела?' }, class: 'btn btn-danger btn-sm' %>
          </div>
        <% end %>

        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title"><%= t('activerecord.attributes.user.credentials') %></legend>
          <div class="checkbox-table">
            <%= f.collection_check_boxes :credential_ids, Credential.all, :id, -> (credential) { t("activerecord.attributes.credential.key.#{credential.key}") } do |cb| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= cb.label %>
                </div>
                <div class="checkbox-input">
                  <%= cb.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>


        <div class="form-actions">
          <%= f.submit 'Сохранить изменения', class: 'btn btn-primary btn-md' %>
          <%= link_to 'Удалить пользователя', user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Удалить пользователя #{@user.login}?" }, class: 'btn btn-danger btn-sm' %>
        </div>


      <% end %>

    <% else %>

      <% if current_user.can_edit_own_profile? %>
        <%= form_for current_user, url: user_path(current_user), method: :patch do |f| %>
          <div class="form-field">
            <%= f.label :login %>
            <%= f.text_field :login, autofocus: true %>
          </div>

          <div class="form-field">
            <%= f.label "Имя" %>
            <%= f.text_field :first_name %>
          </div>

          <div class="form-field">
            <%= f.label "Фамилия" %>
            <%= f.text_field :last_name %>
          </div>

          <div class="form-field">
            <%= f.label :email %>
            <%= f.email_field :email %>
          </div>

          <div class="form-action">
            <%= f.submit 'Сохранить', class: 'btn btn-primary btn-sm' %>
          </div>
        <% end %>

      <% else %>
        У вас недостаточно прав для редактирования своего профиля.
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_users.erb
<%= turbo_frame_tag "left-column" do %>
  <% users = User.all.order created_at: :desc %>
  <div class="list-wrapper">
    <div class="list-title column-title">
      <div class="title-menu">
        <div class="title-text">
          Пользователи [<%= User.count %>]
        </div>
        <div class="plus-button_wrapper">
          <%= button_to '+', new_user_registration_path, data: { turbo_frame: "user-new" }, class: "plus-button btn btn-primary", method: :get %>
        </div>
      </div>
      <div class="menu-button-wrapper">
        <%= button_to 'Роли', roles_path, data: { turbo_frame: "left-column" }, method: :get, class: "roles-button btn btn-primary" %>
      </div>
      <div class="menu-button-wrapper">
        <%= button_to 'Отделы', departments_path, data: { turbo_frame: "left-column" }, method: :get, class: "departments-button btn btn-primary" %>
      </div>
    </div>


    <div class="list-container">
      <% users.each do |user| %>
        <div class="item">
          <%= turbo_frame_tag user do %>
            <div class="item-links">
              <% user = UserDecorator.decorate(user) %>
              <%= link_to user.show_full_name, user_path(user), class: "item-name", data: { turbo_frame: "user-info" } %>
              <div class="item-actions">
                <%= link_to 'Инфо', user_path(user), class: "link", data: { turbo_frame: "user-info" } %>
                <%= link_to 'Изменить', edit_user_path(user), method: :get, class: "link", data: { turbo_frame: "user-edit" } %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
