config/routes.rb
Rails.application.routes.draw do
  get 'results/index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
  }
  root 'articles#index'

  get 'upanel', to: 'static#upanel', as: 'upanel'

  namespace :admin do
    get 'cpanel', to: 'admin#cpanel', as: 'cpanel'
    resources :users do
      member do
        patch 'remove_from_department', to: 'users#remove_from_department'
      end
    end
    resources :departments
    resources :roles
    get 'history', to: 'history#index', as: 'history'
  end

  resources :secure_records
  resources :notes
  resources :articles

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/role.rb
class Role < ApplicationRecord
  validates :key, presence: true, uniqueness: true
  audited
  has_many :users

  def show_name
    if self.name.present?
      self.name
    else
      self.key
    end
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :require_admin?

  def index
    @roles = Role.all.order created_at: :desc
  end

  def show
    @search_results = User.search_everywhere(params[:query])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new roles_params
    if @role.save
      flash[:notice] = "Роль успешно создана."
    else
      flash[:alert] = @role.errors.full_messages.join("<br>").html_safe
    end
  end

  def edit
  end

  def update
    if @role.update roles_params
      flash.now[:notice] = "Роль успешно обновлена."
    else
      flash.now[:alert] = @role.errors.full_messages.join("<br>").html_safe
    end
  end

  def destroy
    if @role.users.present?
      flash.now[:alert] = "Роль не может быть удалена, так как в ней присутствуют пользователи."
    elsif @role.destroy
      flash.now[:alert] = "Роль успешно удалена."
    else
      flash.now[:alert] = @role.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def roles_params
    params.require(:role).permit(:key, :name, user_ids: [])
  end

  def set_role
    @role = Role.find(params[:id])
  end

  def require_admin?
    unless current_user.admin?
      render :plain => 'Вы не администратор'
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all.order created_at: :desc
  end

  def show
    @search_results = User.search_everywhere(params[:query])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new roles_params
    if @role.save
      flash[:notice] = "Роль успешно создана."
    else
      flash[:alert] = @role.errors.full_messages.join("<br>").html_safe
    end
  end

  def edit
  end

  def update
    if @role.update roles_params
      flash.now[:notice] = "Роль успешно обновлена."
    else
      flash.now[:alert] = @role.errors.full_messages.join("<br>").html_safe
    end
  end

  def destroy
    if @role.users.present?
      flash.now[:alert] = "Роль не может быть удалена, так как в ней присутствуют пользователи."
    elsif @role.destroy
      flash.now[:alert] = "Роль успешно удалена."
    else
      flash.now[:alert] = @role.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def roles_params
    params.require(:role).permit(:key, :name, user_ids: [])
  end

  def set_role
    @role = Role.find(params[:id])
  end
end

app/views/admin/roles/_form_edit.erb
<%= turbo_frame_tag "role-edit" do %>
  <div class="center-and-right-column column-title">
    Редактирование роли
    <div class="title-login">
      <%= @role.show_name %>
    </div>
    <button class="close-turbo-frame btn btn-danger" data-frame-id="role-edit">X</button>
  </div>

  <div class="form-wrapper">

    <%= form_for @role, url: admin_role_path(@role), method: :patch, html: { class: 'form-edit'} do |f| %>

<!--      <div id="flash">-->
        <%#= render partial: 'shared/flash' %>
<!--      </div>-->

      <div class="form-field">
        <%= f.label :key, 'Ключ' %>
        <%= f.text_field :key, autofocus: true, required: true %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Название' %>
        <%= f.text_field :name %>
      </div>

      <% if @role.users.present? %>

        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title">Пользователи с этой ролью</legend>

          <div class="checkbox-table">
            <%= f.collection_check_boxes :user_ids, @role.users, :id, -> (user) { UserDecorator.decorate(user).show_full_name } do |user| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= user.label %>
                </div>
                <div class="checkbox-input">
                  <%= user.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>
      <% end %>

      <% if User.where(role_id: nil).present? %>
        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title">Пользователи без роли</legend>

          <div class="checkbox-table">
            <%= f.collection_check_boxes :user_ids, User.where(role_id: nil), :id, -> (user) { UserDecorator.decorate(user).show_full_name } do |user| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= user.label %>
                </div>
                <div class="checkbox-input">
                  <%= user.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>
      <% end %>

      <div class="form-actions">
        <%= f.submit 'Сохранить изменения', class: 'btn btn-lg' %>
        <%= link_to 'Удалить роль', admin_role_path(@role), data: { turbo_method: :delete, turbo_confirm: "Удалить роль #{@role.key}?" }, class: 'btn btn-danger btn-lg' %>
      </div>

    <% end %>
  </div>
<% end %>

app/views/admin/roles/_form_new.erb
<%= turbo_frame_tag "role-new" do %>
  <div class="center-and-right-column column-title">
    Создание новой роли
    <button class="close-turbo-frame btn btn-danger" data-frame-id="role-new">X</button>
  </div>
  <div class="form-wrapper">
    <%= form_with model: @role, url: admin_roles_path, local: true, html: { class: 'form-edit' }  do |f| %>

<!--      <div id="flash">-->
        <%#= render partial: 'shared/flash' %>
<!--      </div>-->

      <div class="form-field">
        <%= f.label :key, 'Ключ' %>
        <%= f.text_field :key, autofocus: true, required: true %>
      </div>
      <div class="form-field">
        <%= f.label :name, 'Название' %>
        <%= f.text_field :name %>
      </div>
      <div class="form-actions">
        <%= f.submit 'Сохранить', class: 'btn btn-lg' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/roles/_role_info.erb
<%= turbo_frame_tag "role-info" do %>
  <div class="center-and-right-column column-title">
    Информация о роли
    <div class="title-login">
      <%= @role.show_name %>
    </div>
    <button class="close-turbo-frame btn btn-danger" data-frame-id="role-info">X</button>
  </div>

  <div class="show-wrapper role-show-wrapper">
    <div class="show-container">

      <div class="info-container">

        <div class="form-wrapper">
          <%= form_tag admin_role_path(@role), method: :get, role: 'search' do %>
            <div class="form-field search-wrapper">
              <%= text_field_tag :query, params[:query], placeholder: 'Имя\Фамилия\Логин\Почта', class: 'search-field' %>
              <%= submit_tag 'Поиск', class: 'btn btn-lg' %>
            </div>
          <% end %>
        </div>

        <% if @search_results.where(role_id: @role).present? %>
          <br>
          Результаты поиска : <br>
          <% @search_results.where(role_id: @role).each do |result| %>
            <details class="show-item">
              <summary class="item-links">
                <% result = UserDecorator.decorate(result) %>
                <%= link_to result.show_full_name, admin_user_path(result), class: "item-name", data: { turbo_frame: "user-info" } %>
              </summary>
              <div class="user-email">
                <%= result.email %>
              </div>
              <div class="user-department">
                <%= result.department.name %>
              </div>
              <div class="item-actions">
                <%= link_to 'Инфо', admin_user_path(result), class: "link", data: { turbo_frame: "user-info" } %>
                <%= link_to 'Изменить', edit_admin_user_path(result), method: :get, class: "link", data: { turbo_frame: "user-edit" } %>
              </div>
            </details>
          <% end %>
          <br>
        <% end %>

        <div class="users-table">
          <% if @role.users.present? %>
            <% @role.users.each do |user| %>
              <details class="show-item">
                <summary class="item-links">
                  <% user = UserDecorator.decorate(user) %>
                  <%= link_to user.show_full_name, admin_user_path(user), class: "item-name", data: { turbo_frame: "user-info" } %>
                </summary>
                <div class="user-email">
                  <%= user.email %>
                </div>
                <div class="user-department">
                  <% if user.department.present? %>
                    <%= user.department.name %>
                  <% else %>
                    Отдел не назначен
                  <% end %>
                </div>
                <div class="item-actions">
                  <%= link_to 'Инфо', admin_user_path(user), class: "link", data: { turbo_frame: "user-info" } %>
                  <%= link_to 'Изменить', edit_admin_user_path(user), method: :get, class: "link", data: { turbo_frame: "user-edit" } %>
                </div>
              </details>
            <% end %>
          <% else %>
            <p>Пользователи не найдены</p>
          <% end %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/admin/roles/_roles.erb
<%= turbo_frame_tag "left-column" do %>
  <% roles = Role.all.order created_at: :desc %>
  <div class="list-wrapper">
    <div class="list-title column-title">
      <div class="menu-button-wrapper">
        <%= button_to 'Пользователи', admin_users_path, data: { turbo_frame: "left-column"}, method: :get, class: "menu-button" %>
      </div>
      <div class="title-menu">
        <div class="title-text">
          Роли
        </div>
      </div>
      <div class="menu-button-wrapper">
        <%= button_to 'Отделы', admin_departments_path, data: { turbo_frame: "left-column"}, method: :get, class: "menu-button" %>
      </div>
    </div>

      <%= button_to 'Создать новую роль', new_admin_role_path, data: { turbo_frame: "role-new" }, class: "plus-btn", method: :get %>

    <div class="list-container">
      <% roles.each_with_index do |role, index| %>
        <div class="item <%= index.odd? ? 'odd' : 'even' %>">
          <%= turbo_frame_tag role do %>
            <div class="item-links">
              <%= link_to (role.name.present? ? role.name : role.key), admin_role_path(role), class: "item-name", data: { turbo_frame: "role-info" } %>
              <div class="item-actions">
                <%= link_to 'Инфо', admin_role_path(role), class: "link", data: { turbo_frame: "role-info" } %>
                <%= link_to 'Изменить', edit_admin_role_path(role), method: :get, class: "link", data: { turbo_frame: "role-edit" } %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>


app/views/admin/roles/create.turbo_stream.erb
<%= turbo_stream.update("left-column") do
  render 'roles'
end %>

<%#= prepend_flash %>

app/views/admin/roles/destroy.turbo_stream.erb
<%= turbo_stream.remove @role %>

<%= turbo_stream.update("role-edit") do
  render 'shared/flash'
end %>

app/views/admin/roles/edit.html.erb
<%= render 'form_edit' %>

app/views/admin/roles/index.html.erb
<%= turbo_frame_tag "left-column" do %>
  <%= render 'roles' %>
<% end %>

app/views/admin/roles/new.html.erb
<%= render 'form_new' %>

app/views/admin/roles/show.html.erb
<%= render 'role_info' %>

app/views/admin/roles/update.turbo_stream.erb
<%= turbo_stream.update("role-edit") do
  render 'form_edit'
 end %>

<%= turbo_stream.update("left-column") do
  render 'roles'
end %>

<%#= prepend_flash %>