config/routes.rb
Rails.application.routes.draw do
  get 'results/index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
  }
  root 'articles#index'

  get 'upanel', to: 'static#upanel', as: 'upanel'

  namespace :admin do
    get 'cpanel', to: 'admin#cpanel', as: 'cpanel'
    resources :users do
      member do
        patch 'remove_from_department', to: 'users#remove_from_department'
      end
    end
    resources :departments
    resources :roles
    get 'history', to: 'history#index', as: 'history'
  end

  resources :secure_records
  resources :notes
  resources :articles

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_everywhere, against: [:login, :email, :first_name, :last_name]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :trackable, :timeoutable,
         :registerable

  validates :login, :email, presence: true, uniqueness: true
  validates :department_id, allow_nil: true, presence: true

  belongs_to :role
  belongs_to :department
  has_and_belongs_to_many :credentials
  has_many :secure_records
  has_many :notes

  audited


  # role definition
  def admin?
    self.role.key == 'admin'
  end

  # credentials check

  def can_edit_own_profile? # ok
    self.credentials.include?(Credential.find_by(key: 'can_edit_own_profile'))
  end

  def can_edit_user?
    User.find_by(id: self.id).credentials.include?(Credential.find_by(key: 'can_edit_user'))
  end

  def can_assign_department_to_user?
    User.find_by(id: self.id).credentials.include?(Credential.find_by(key: 'can_assign_department_to_user'))
  end

  def can_working_with_articles?
    User.find_by(id: self.id).credentials.include?(Credential.find_by(key: 'can_working_with_articles'))
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user!, only: %i[show edit update destroy]
  before_action :require_admin?

  def index
    @users = User.order created_at: :desc
    @search_results = User.search_everywhere(params[:query])
  end

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      flash.now[:notice] = "Пользователь успешно обновлен"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def destroy
    if @user.admin?
      flash.now[:alert] = "Нельзя удалить администратора"
      return
    end

    if @user.destroy
      flash.now[:alert] = "Пользователь успешно удален"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def remove_from_department
    @user = User.find(params[:id])
    @user.department = nil
    if @user.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("user-info", partial: "user_info") }
      end
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :first_name, :last_name, :department_id, :password, :role_id, credential_ids: [])
  end

  def set_user!
    @user = User.find(params[:id]).decorate
  end

  def require_admin?
    unless current_user.admin?
      render :plain => 'Вы не администратор'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user!, only: %i[show edit update destroy]

  def index
    @users = User.order created_at: :desc
  end

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      flash.now[:notice] = "Пользователь успешно обновлен"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def destroy
    if @user.admin?
      flash.now[:alert] = "Нельзя удалить администратора"
      return
    end

    if @user.destroy
      flash.now[:alert] = "Пользователь успешно удален"
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  def remove_from_department
    @user = User.find(params[:id])
    @user.department_id = Department.find_by(key: "nil_department", name: "Нулевой отдел").id
    if @user.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("user-info", partial: "user_info") }
      end
    else
      flash.now[:alert] = @user.errors.full_messages.join("<br>").html_safe
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :first_name, :last_name, :department_id, :password, :role_id, credential_ids: [])
  end

  def set_user!
    @user = User.find(params[:id]).decorate
  end

end

app/views/admin/users/_form_edit.erb
<%= turbo_frame_tag "user-edit" do %>

  <div class="center-and-right-column column-title">
    <% if current_user.can_edit_user? %>
      Редактирование пользователя
      <div class="title-login">
        <%= @user.show_full_name %>
      </div>
    <% else %>
      <div class="title-login">
        Редактирование вашего профиля
      </div>
    <% end %>
    <button class="close-turbo-frame btn btn-danger" data-frame-id="user-edit">X</button>
  </div>

  <div class="form-wrapper">

    <% if current_user.can_edit_user? %>

      <%= form_for @user, url: admin_user_path(@user), method: :patch, html: { class: "form-edit" } do |f| %>

        <!--        <div id="flash">-->
        <%#= render partial: 'shared/flash' %>
        <!--        </div>-->

        <div class="form-field">
          <%= f.label t('activerecord.attributes.user.login') %>
          <%= f.text_field :login, autofocus: true, required: true %>
        </div>

        <div class="form-field">
          <%= f.label "Email" %>
          <%= f.email_field :email %>
        </div>

        <div class="form-field">
          <%= f.label t('activerecord.attributes.user.first_name') %>
          <%= f.text_field :first_name %>
        </div>

        <div class="form-field">
          <%= f.label t('activerecord.attributes.user.last_name') %>
          <%= f.text_field :last_name %>
        </div>

        <div style="display: flex; justify-content: space-between">
          <div class="form-field">
            <%= f.label t('activerecord.attributes.user.role') %>
            <%= f.collection_select :role_id, Role.all, :id, -> (role) { role.name.present? ? role.name : role.key } %>
          </div>

          <% if current_user.can_assign_department_to_user? %>
            <div class="form-field">
              <%= f.label t('activerecord.attributes.user.department_id') %>
              <%= f.collection_select :department_id, Department.all, :id, :name, :selected => @user.department_id %>
              <%#= link_to 'Удалить из отдела', remove_from_department_admin_user_path(@user), data: { turbo_method: :patch, turbo_confirm: 'Удалить пользователя из отдела?' }, class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>

        <fieldset class="checkbox-wrapper">
          <legend class="checkbox-table-title"><%= t('activerecord.attributes.user.credentials') %></legend>
          <div class="checkbox-table">
            <%= f.collection_check_boxes :credential_ids, Credential.all, :id, :name do |cb| %>
              <div class="checkbox-table-item">
                <div class="checkbox-label">
                  <%= cb.label %>
                </div>
                <div class="checkbox-input">
                  <%= cb.check_box %>
                </div>
              </div>
            <% end %>
          </div>
        </fieldset>


        <div class="form-actions">
          <%= f.submit 'Сохранить изменения', class: 'btn btn-lg' %>
          <%= link_to 'Удалить пользователя', admin_user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Удалить пользователя #{@user.show_full_name}?" }, class: 'btn btn-lg btn-danger' %>
        </div>


      <% end %>

    <% else %>

      <% if current_user.can_edit_own_profile? %>
        <%= form_for current_user, url: admin_user_path(current_user), method: :patch, html: { class: "form-edit" } do |f| %>

          <div class="form-field">
            <%= f.label :login %>
            <%= f.text_field :login, autofocus: true %>
          </div>

          <div class="form-field">
            <%= f.label "Имя" %>
            <%= f.text_field :first_name %>
          </div>

          <div class="form-field">
            <%= f.label "Фамилия" %>
            <%= f.text_field :last_name %>
          </div>

          <div class="form-field">
            <%= f.label "Email" %>
            <%= f.email_field :email %>
          </div>

          <div class="form-action">
            <%= f.submit 'Сохранить', class: 'btn btn-primary btn-lg' %>
          </div>
        <% end %>

      <% else %>
        У вас недостаточно прав для редактирования своего профиля.
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/users/_user_info.erb
<%= turbo_frame_tag "user-info" do %>
  <div class="center-and-right-column column-title">Информация о пользователе
    <div class="title-login"><%= @user.show_full_name %></div>
    <button class="close-turbo-frame btn btn-danger" data-frame-id="user-info">X</button>
  </div>
  <div class="show-wrapper">
    <div class="show-container">
      <fieldset class="main-info info-container">
        <legend>Основная информация</legend>
        <div class="show-item">
          <div>
            <b>ID : </b>
            <%= @user.id %>
          </div>
        </div>

        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.login') %> :</b>
            <% if @user.login.present? %>
              <%= @user.login %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>

        <div class="show-item">
          <div>
            <b><%= t('activerecord.attributes.user.first_name') %> :</b>
            <% if @user.first_name.present? %>
              <%= @user.first_name %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>

        <div class="show-item">
          <div>
            <b><%= t('activerecord.attributes.user.last_name') %> :</b>
            <% if @user.last_name.present? %>
              <%= @user.last_name %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>

        <div class="show-item">
          <div>
            <b><%= t('activerecord.attributes.user.email') %> :</b>
            <% if @user.email.present? %>
              <%= @user.email %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>

        <div class="show-item">
          <div>
            <b><%= t('activerecord.attributes.user.department_id') %> :</b>
            <% if @user.department.present? %>
              <%= @user.department.name %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>

        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.role') %> :</b>
            <% if @user.role.present? %>
              <% @user = @user.decorate %>
              <%= @user.show_role %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>

        <div class="show-actions">
          <%= button_to 'Редактировать', edit_admin_user_path(@user), method: :get, data: { turbo_frame: "user-edit" }, class: "btn btn-warning" %>
        </div>
      </fieldset>

      <fieldset class="credentials-wrapper info-container">
        <legend class="credentials-title"><%= t('activerecord.attributes.user.credentials') %></legend>
        <% if @user.credentials.any? %>
          <div class="credentials-table">
            <% @user.credentials.each do |credential| %>
              <div class="credentials-table-item">
                <div class="credential">
                  <%= credential.name %>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <b><%= t('activerecord.errors.messages.no_data') %></b>
        <% end %>
      </fieldset>


      <fieldset class="technical-user-info info-container">
        <legend>Техническая информация</legend>
        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.current_sign_in_ip') %> : </b>
            <% if @user.current_sign_in_ip.present? %>
              <%= @user.current_sign_in_ip %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>
        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.last_sign_in_ip') %> :</b>
            <% if @user.last_sign_in_ip.present? %>
              <%= @user.last_sign_in_ip %>
            <% else %>
              <%= render 'shared/no_data_message' %>
            <% end %>
          </div>
        </div>
      </fieldset>

      <fieldset class="timestamps-user-info info-container">
        <legend>Временные метки</legend>
        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.last_sign_in_at') %> :</b>
            <% if @user.last_sign_in_at.present? %>
              <%= @user.formatted_last_sign_in_at %>
            <% else %>
              <%= t('activerecord.errors.messages.no_data') %>
            <% end %>
          </div>
        </div>
        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.created_at') %> :</b> <%= @user.formatted_created_at %></div>
        </div>
        <div class="show-item">
          <div><b><%= t('activerecord.attributes.user.updated_at') %> :</b> <%= @user.formatted_updated_at %></div>
        </div>
      </fieldset>
      

    </div>
  </div>
<% end %>

app/views/admin/users/_users.erb
<%= turbo_frame_tag "left-column" do %>
  <% users = User.all.order created_at: :desc %>
  <div class="list-wrapper">
    <div class="list-title column-title">
      <div class="title-menu">
        <div class="title-text">
          Пользователи
        </div>
      </div>
      <div class="menu-button-wrapper">
        <%= button_to 'Роли', admin_roles_path, data: { turbo_frame: "left-column" }, method: :get, class: "menu-button" %>
      </div>
      <div class="menu-button-wrapper">
        <%= button_to 'Отделы', admin_departments_path, data: { turbo_frame: "left-column" }, method: :get, class: "menu-button" %>
      </div>
    </div>

    <div class="list-actions">
      <%= button_to 'Создать нового пользователя', new_user_registration_path, data: { turbo_frame: "user-new" }, class: "plus-btn", method: :get %>

      <div class="search-field">
        <input type="text" placeholder="Поиск" class="search-input" id="search-user" data-controller="search_user" data-action="input->search_user#search">
      </div>
    </div>

    <div class="list-container">

      <% users.each_with_index do |user, index| %>
        <% user = UserDecorator.decorate(user) %>
        <div class="item user-item <%= index.odd? ? 'odd' : 'even' %>" data-name="<%= user.show_full_name %>" data-email="<%= user.email %>" data-login="<%= user.login %>">
          <%= turbo_frame_tag user do %>
            <div class="item-links">
              <% user = UserDecorator.decorate(user) %>
              <%= link_to user.show_full_name, admin_user_path(user), class: "item-name", data: { turbo_frame: "user-info" } %>
              <div class="item-actions">
                <%= link_to 'Инфо', admin_user_path(user), class: "link", data: { turbo_frame: "user-info" } %>
                <% if current_user.can_edit_user? %>
                  <%= link_to 'Изменить', edit_admin_user_path(user), method: :get, class: "link", data: { turbo_frame: "user-edit" } %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/users/destroy.turbo_stream.erb
<%= turbo_stream.update "left-column" do
  render 'users'
end %>

<%= turbo_stream.update "user-edit" do
  render 'shared/flash'
end %>

app/views/admin/users/edit.erb
<%= render 'form_edit' %>

app/views/admin/users/index.erb
<%= turbo_frame_tag "left-column" do %>
  <%= render 'users' %>
<% end %>

app/views/admin/users/show.erb
<%= render 'user_info' %>

app/views/admin/users/update.turbo_stream.erb
<%= turbo_stream.update("left-column") do
  render 'users'
end %>

<%= turbo_stream.update("user-info") do
  render 'user_info'
end %>

<%#= prepend_flash %>